### ISSUE TITLE
How to run two eslint configuration ?

### ISSUE THREAD

**Issue by SebastienElet** [neoclide/coc-eslint#101]
My team use an eslint config which is not enough strict for me.
I love learning new things / habit with eslint ( like https://github.com/jfmengels/eslint-plugin-fp ) and improve my code quality (with complexity for example : https://eslint.org/docs/rules/complexity).

My question is how i would run my personal set of rules in addition of the rules used by my projects ?

**Comment by chemzqm** [comment]
We don't such support, maybe you can ask maintainer of eslint.

**Comment by SebastienElet** [comment]
Thanks for the feedback, I will ask.
