### ISSUE TITLE
Got error when run new project

### ISSUE THREAD

**Issue by dinhmai74** [neoclide/coc-eslint#103]
I got warning Prettier ESLint not approved or denied yet. How can I fix it?

**Comment by chemzqm** [comment]
Read readme.

**Comment by metal3d** [comment]
I read the README and there is no mention about this error. Please reopen

**Comment by metal3d** [comment]
To answer to anyone that don't find the solution, type `:CocCommand eslint.showOutputChannel` and approve the execution.

@chemzqm there are many stuffs that are not OK inside the README file, this command is missing and there is "eslint.enable" witch is not valid since several versions.

Regards,

**Comment by chemzqm** [comment]
Checkout `:h coc_status` to enable status line support.

**Comment by metal3d** [comment]
OK, I had this line but I need to launch the showOutputChannel command anyway. 

That's weird but CocConfig gives me an error when I set `eslint.enable` to true... I'm checking again.

**Comment by metal3d** [comment]
![image](https://user-images.githubusercontent.com/100080/108954027-6e0fb200-766c-11eb-921e-74683316c0a3.png)

**Comment by 1bharat** [comment]
Thanks @metal3d I am getting the same error when setting `eslint.enable: true` in coc-settings.json

I went with `CocCommand eslint.showOutputChannel` and enabled it.
