### ISSUE TITLE
Disable warning

### ISSUE THREAD

**Issue by phaalonso** [neoclide/coc-eslint#104]
How I can disable eslint  warnings?

![image](https://user-images.githubusercontent.com/26033899/107837776-58071500-6d81-11eb-9259-5c1bb019e6c3.png)

![image](https://user-images.githubusercontent.com/26033899/107837781-5f2e2300-6d81-11eb-8e93-0de741bd6f13.png)

**Comment by chemzqm** [comment]
It's warning from coc-json
