### ISSUE TITLE
"eslint.run": "onSave" doesn't work as before

### ISSUE THREAD

**Issue by andbar-ru** [neoclide/coc-eslint#106]
Thanks for your work!

I have this option in coc-settings.com
```
"eslint.run": "onSave"
```

Until updating to the last versions of coc.nvim and all extensions, diagnostics was being updated after every file saving. Now diagnostics is being updated  every time I leave insert mode. Diagnostics messages refer to tsserver and vetur. I assume that "onSave" works correctly for what concerns eslint and tsserver and vetur are beyond of coc-eslint responsibility. But before last updating this configuration option prevented messages from tsserver and vetur until file saving.

My coc-settings.json
<details>
<summary>coc-settings.json</summary>
{<br>
  "coc.preferences.colorSupport": false,<br>
  "coc.preferences.currentFunctionSymbolAutoUpdate": false,<br>
  "coc.preferences.formatOnSaveFiletypes": ["go"],<br>
  "coc.preferences.messageLevel": "error",<br>
  "codeLens.enable": true,<br>
  "diagnostic.errorSign": "E",<br>
  "diagnostic.hintSign": "H",<br>
  "diagnostic.infoSign": "I",<br>
  "diagnostic.virtualText": false,<br>
  "diagnostic.warningSign": "W",<br>
  "eslint.quiet": true,<br>
  "eslint.run": "onSave",<br>
  "eslint.validate": ["javascript", "typescript", "vue"],<br>
  "python.jediEnabled": true,<br>
  "python.linting.enabled": true,<br>
  "python.linting.flake8Args": ["--max-line-length=120"],<br>
  "python.linting.flake8Enabled": true,<br>
  "python.linting.flake8Path": "/usr/bin/flake8",<br>
  "python.linting.pylintEnabled": false,<br>
  "signature.hideOnTextChange": true,<br>
  "suggest.autoTrigger": "none",<br>
  "suggest.noselect": false,<br>
  "vetur.useWorkspaceDependencies": true,<br>
  "vetur.validation.template": false<br>
}<br>
</details>

* Is this intentional modification?
* What should I do to prevent tsserver and vetur updating diagnostics on every leaving of insert mode?

UPDATE: messages from tsserver and vetur happen even if I disable coc-eslint in `CocList extensions` menu.

**Comment by chemzqm** [comment]
It's expected

**Comment by chemzqm** [comment]
Language server doesn't provide lint on save
