### ISSUE TITLE
fails with `extends: react-app`

### ISSUE THREAD

**Issue by davidsu** [neoclide/coc-eslint#107]
I have this non-trivial project that I'm getting into, it's a monorepo where one of the sub-repos has a eslint config extending from a thousand different configs. coc-eslint simply didn't run there, playing around I figured that commenting out the line that `extends` from `react-app` makes coc-eslint behave as expected.
Have you ever come across this?

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders

**Comment by davidsu** [comment]
I don't understand, why/how should this help me?
Once I remove `react-app` eslint works properly, using the correct binary and correct configuration, it's just this specific dependency that causes coc-eslint to fail silently, I don't even know what the problem is, don't know what to add in this workspace.
In any case, I have removed this dependency from eslintrc and I'm fine with it.
I really prefer avoiding project specific ide configurations, so I'm fine with this, just thought to raise your awarness to the situation.
Thanks a lot for your answer and your amazing work!

**Comment by chemzqm** [comment]
Should be issue with your eslint, can't reproduce from your description https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
