### ISSUE TITLE
Add code lens diagnostics

### ISSUE THREAD

**Issue by sevensidedmarble** [neoclide/coc-eslint#108]
I've seen some other coc extensions use the code lens feature to put some nice annotations in buffers. How doable would it be to make coc-eslint display diagnostics inline with code lens similar to https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens ?

**Comment by chemzqm** [comment]
There's only virtual text support for diagnostics `:h coc-config-diagnostic`
