### ISSUE TITLE
[Question] How to format diagnostic message?

### ISSUE THREAD

**Issue by rolfb** [neoclide/coc-eslint#109]
Is there a way to format the diagnostic message, and/or to prevent it from underlining the whole block of code? 
Would love to have no underline here and skip the entire block of code in the diagnostic message.

Tried finding out for myself, but I got stomped. Sorry.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/10254/110966710-da213400-8355-11eb-8190-037efba29d6f.png">
<img width="965" alt="image" src="https://user-images.githubusercontent.com/10254/110966755-e60cf600-8355-11eb-9346-6d3add838024.png">

**Comment by chemzqm** [comment]
No, unless you fork the code.

**Comment by rolfb** [comment]
Ok, was hoping there was some lower level options to apply for the eslint runner/reporter. Appreciate the reply.

**Comment by chemzqm** [comment]
`:h CocWarningHighlight` for change highlights of warning diagnostics.
