### ISSUE TITLE
Coc-eslint doesn't work on my typescript files

### ISSUE THREAD

**Issue by xavierhazzardadmin** [neoclide/coc-eslint#113]
I'm not that experienced with Vim, I only just started using it.

I had coc-eslint working completely fine in my JavaScript files, it gave me errors as soon as I saved. But now as I'm learning typescript and I'm trying to use vim with typescript, it doesn't work.

I don't get any indication of errors in my files and nothing in the diagnostics.

As soon as I switch to the JS, in the same directory, it works.

Please let me know what you need to reproduce this issue. 

Much appreciated.

**Comment by chemzqm** [comment]
Read configuration

**Comment by xavierhazzardadmin** [comment]
> Read configuration

Would you be able to tell me specifically which parts I should be looking at?
I tried to use the `eslint.probes` method but I've still no success.

When I try to run :`CocCommand eslint.lintProject` I get either `TSC error` or `[coc.nvim] TSC error: ESLint: 7.20.0`

I don't really know how to fix this issue and I'm not too keen on switching back to VSCode after all the effort I've gone into making Vim nicer for myself.

**Comment by chemzqm** [comment]
Add your filetype to `eslint.validate` configuration, you also have to configure your eslint to support typescript.

**Comment by xavierhazzardadmin** [comment]
> All configurations are the same as VSCode.
> 
> Add your filetype to `eslint.validate` configuration, you also have to configure your eslint to support typescript.
> 
> Use `"eslint.lintTask.options": [".", "--ext", ".ts"]` configuration for `eslint.lintProject` command

I am so thankful to you. This worked straight away. Thanks so much
