### ISSUE TITLE
Persist "allow everywhere" option for `eslint.showOutputChannel`

### ISSUE THREAD

**Issue by grenmester** [neoclide/coc-eslint#115]
Every time I open `neovim` the following warning shows up

```
ESLint is diabled since its execution has not been approved or denied yet.
Use :CocCommand eslint.showOutputChannel to open the approval dialog.
[eslint:]
```

and I have to run the suggested command to enable ESLint. Is there a way to permanently allow the extension to be used everywhere so I don't have to keep running this command every time I open `neovim`? I've tried looking online and it doesn't seem like anyone else has run into this problem so I'm not sure if I'm missing something here.

**Comment by chemzqm** [comment]
It should not prompt for same workspace folder, can't reproduce.

**Comment by grenmester** [comment]
Tried it on a separate machine and as you said, this doesn't happen. Not sure what exactly was happening on my machine so I tried uninstalling and reinstalling `coc-eslint`. This unfortunately didn't work; however, I was able to get rid of this reappearing ESLint warning by uninstalling `coc.nvim`, wiping the `~/.config/coc` directory, and reinstalling `coc.nvim` and `coc-eslint`.
