### ISSUE TITLE
Doesn't work with esLint 8.x

### ISSUE THREAD

**Issue by timshannon** [neoclide/coc-eslint#117]
I believe due to this: https://eslint.org/blog/2021/06/whats-coming-in-eslint-8.0.0#removal-of-undocumented-apis-removal-of-cliengine-and-linter

Eslint works fine from the command line, but I"m getting this error in VIM:

```The eslint library loaded from [.....]/node_modules/eslint/lib/api.js doesn't export a CLIEngine. You need at least eslint@1.0.0```

I believe vscode-eslint has already implemented these changes:

https://github.com/microsoft/vscode-eslint/issues/972

**Comment by duykhoa** [comment]
For those who are looking for the answer like me, the solution can be found in [@fannheyward  comment](https://github.com/neoclide/coc-eslint/pull/118#issuecomment-973640987)

**Comment by oguzhannsahinn** [comment]
I got the same issue about eslint. If you update the vsCode, eslint will working.
