### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by abienz** [neoclide/coc-eslint#119]
I have a simple JS file and I'm expecting to see warnings/errors as I'm working/saving but am not seeing any feedback.

I'm running on nvim with coc.nvim and coc-eslint installed (via :CocInstall coc-eslint).

Checking the output I can see that ESlint is running on nodejs 14.x.x, so it appears to be installed and working correctly through nvim.

my JS file is as follows...

index.js
```
"strict mode"

undefined = 4;
Infinity = 5;
```
I'm expecting to see type errors regarding these two statements, am I misunderstanding how to use coc-eslint?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

Seems your eslint is disabled for that project.

**Comment by chemzqm** [comment]
coc-eslint has bug with files not on the disk, you need save the file and restart eslint server.
