### ISSUE TITLE
[Question] Eslint config on project level

### ISSUE THREAD

**Issue by adamgajzlerowicz** [neoclide/coc-eslint#12]
I am using the plugin and it is awesome! Thank you!

I have a question though - How can I provide a per project config?

for example in one project I'd like to use 
` "eslint.nodePath": "~/projects/xx/frontend/node_modules"`
but for the other one 
`` "eslint.nodePath": "~/projects/yy/node_modules",``

Is there a way to do this please? I am not sure if this is on plugin or coc level. 

Thank you

**Comment by chemzqm** [comment]
Sure, just use folder configuration file https://github.com/neoclide/coc.nvim/wiki/Using-configuration-file

**Comment by adamgajzlerowicz** [comment]
Thank you!

**Comment by edrpls** [comment]
FYI: The link was updated to: https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file

**Comment by ddiegosr** [comment]
Someone have a example of how to use the folder configuration in configuration file?

**Comment by chemzqm** [comment]
Create `.vim/coc-settings.json` then add your json configuration.
