### ISSUE TITLE
Eslint 8 support 

### ISSUE THREAD

**Issue by ravisumit33** [neoclide/coc-eslint#126]
Currently this extension doesn't work with Eslint version 8.
I get error saying `CLIEngine is not exported`. Looks like it relates to https://github.com/microsoft/vscode-eslint/issues/1329 and according to them it will be fixed with their v2.2.0 (https://github.com/microsoft/vscode-eslint/issues/972#issuecomment-932335309)

What is the plan of coc-eslint for this ?

**Comment by chemzqm** [comment]
Could be your coc-eslint need upgrade https://github.com/neoclide/coc-eslint/blob/master/package.json#L171
