### ISSUE TITLE
Could not find a declaration file for module - how to get rid of it?

### ISSUE THREAD

**Issue by adamgajzlerowicz** [neoclide/coc-eslint#13]
My project is not in ts but in js. Seems that tsserver reports this as a lint error

`Could not find a declaration file for module 'redux-notifications'. '/Users/adam/projects/ad/node_modules/redux-notifications/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/redux-notifications` if it exists or add a new declaration (.d.ts) file containing `declare module 'redux-notifications';``

This message also comes in vscode, but is almost invisible - it comes when hovered three dots (`...`)
![image](https://user-images.githubusercontent.com/675615/57985772-3cb48c00-7a6d-11e9-8fb1-7aa81d2cb01f.png)

But in vim it shows as a lint warning:
![image](https://user-images.githubusercontent.com/675615/57985746-b5ffaf00-7a6c-11e9-893c-df3c4e90d422.png)

Which means that across entire codebase I get warnings. I'd like to be able to turn them off somehow. Installing typings removes the error, but I don't want to add typings to a js project.
I also tried setting `noImplicitAny` in jsconfig, but the warning still shows.

Have you got any suggestions on how to suppress them?

Thank you!

**Comment by chemzqm** [comment]
It's hint, not warning, checkout https://github.com/neoclide/coc-tsserver#configuration-options for available options.

**Comment by expelledboy** [comment]
@adamgajzlerowicz https://github.com/neoclide/coc-tsserver/issues/89
