### ISSUE TITLE
Is there any configuration for easily opening a recommendation link?

### ISSUE THREAD

**Issue by ramuyk** [neoclide/coc-eslint#132]
Hi,

I'm struggling a little with finding out a way to go to the recommended links on `coc-eslint`... Considering I have a vim configuration which doesn't use `set mouse=a` I can right-click the popup as the following:

![Screenshot_20220523_233301](https://user-images.githubusercontent.com/44415096/169937087-ac9ab073-da48-4b3c-88d2-6972ab268b97.png)

However, in this example it'll break the link in two lines and only capture `https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/` (it'll miss `display-name.md` on the link). If I use a configuration `set mouse=a` it's worse because I can't right-click the recommended link, I need to use a workaround like using `set mouse=nich` just so I still have the option of right-clicking it while the text is  in Visual mode.

I'm not sure if I'm missing some functionality on `coc-eslint`... But since `eslint` always recommends documentation links it would be nice having an easy way of going to the link. Is it currently possible?

**Comment by chemzqm** [comment]
`:h CocAction('openlink')` focus the window by `<C-w>w` if it's focusable.
