### ISSUE TITLE
The "initializing eslint" notification never disappears

### ISSUE THREAD

**Issue by noomly** [neoclide/coc-eslint#133]
As said in the title the notification popup never disappears and the loading animation never stops. Needless to say it's very distracting, especially since I couldn't find how to disable this "vscode-like notification"....

There is also an error displayed in the statusline when coc-eslint is loaded, reading: `[coc.nvim]: Uncaught exception: this._resolve is not a function`.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by noomly** [comment]
Thank you!
