### ISSUE TITLE
[bug] Diagnostic level hard-coded to Unnecessary/Warning/1 for no-unused-vars rule

### ISSUE THREAD

**Issue by jeffzyliu** [neoclide/coc-eslint#134]
In this line, https://github.com/neoclide/coc-eslint/blob/0344fd0f1631c77d65730c465387d9c2989d2532/server/eslintServer.ts#L620-L622
there is the following check:
```js
    if (problem.ruleId === 'no-unused-vars') {
      result.tags = [DiagnosticTag.Unnecessary]
    }
```
This sets all `no-unused-vars` warnings to warning level, regardless of what the user has in their eslint config.
This is not desired behavior since the user should choose the error level `'no-unused-vars'` from none/warning/error themselves.

I'm happy to PR to remove this since I tested removing it from the package code, but I don't know how to fully run tests if they exist.

**Comment by jeffzyliu** [comment]
Edit: this isn't the real "source" of the bug; the upstream vscode plugin has these lines too.

It's in the way coc.nvim handles DiagnosticTags. I'll make a new issue on coc.nvim and link later.

**Comment by chemzqm** [comment]
`CocUnusedHighlight` have higher priority, try `hi clear CocUnusedHighlight` in your vimrc.

**Comment by jeffzyliu** [comment]
Thanks for the response, it's not related to the highlight though. It changes the diagnostic level itself, there's no overriding highlight. Opening an issue in coc.nvim soon.
