### ISSUE TITLE
ESLint 8 flat config support

### ISSUE THREAD

**Issue by 43081j** [neoclide/coc-eslint#137]
As far as i can tell, this doesn't work with eslint's new flat configs (`eslint.config.js`).

From the docs:

>  If you are using the API, you can use the configuration system described on this page by using the FlatESLint class, the FlatRuleTester class, or by setting configType: "flat" in the Linter class.

so it sounds like we would need to conditionally use `FlatESLint` rather than `ESLint` some place.

does that belong here or in the vscode-eslint repo? (not sure if this is updated from the fork or just came from it originally)

i suppose this type would need extending:

https://github.com/neoclide/coc-eslint/blob/0344fd0f1631c77d65730c465387d9c2989d2532/server/eslintServer.ts#L366-L379

to include `FlatESLint` and elsewhere we conditionally load that (maybe need an explicit setting from the user?)

**Comment by chemzqm** [comment]
Need add support for it.

**Comment by 3rdManRun** [comment]
Updated one of my project configs to Flat config and I've lost all diagnostics. Tsserver's all I got going rn. Support needed ASAP

**Comment by 43081j** [comment]
it looks like vscode-eslint has support already:

https://github.com/microsoft/vscode-eslint/blob/f095ba58a6bbefd5b7e5ddcff778f3f04551f554/server/src/eslint.ts#L869-L889

so maybe we just need to somehow merge it into this? no clue what process has been followed for keeping this up to date with the thing it was forked from
