### ISSUE TITLE
Parsing error: ESLint was configured to run on .... However that TSConfig does not include this file

### ISSUE THREAD

**Issue by wikanonymous-dev** [neoclide/coc-eslint#138]
Hi, im just facing problem with configured `.eslintrc.js` and `tsconfig.eslint.json`.
coc-eslint gave me error that files not included either at tsconfig or eslintrc (means that coc-eslint work with my eslint configuration) but I don't know why coc-eslint still gave me that error.

Error occured inside `/src` directory.

Related dependecies version:
```
coc-eslint: 1.5.8
eslint: 8.23.1
```

`.eslintrc.js`

```
> module.exports = {
>   extends: [
>     'standard-with-typescript',
>     'plugin:vue/vue3-recommended',
>     '@vue/eslint-config-typescript',
>     'plugin:unicorn/recommended',
>   ],
>   plugins      : ['align-assignments', 'unicorn'],
>   parserOptions: {
>     project: './tsconfig.eslint.json',
>     parser : {
>       'ts'        : '@typescript-eslint/parser',
>       'js'        : 'espree',
>       '<template>': 'espree',
>     },
>   },
> }
```

`tsconfig.eslint.json`

```
> {
>   "extends": "./tsconfig.json",
>   "include": [
>     "src/**/*.vue",
>     "src/**/*.ts",
>     "src/.vitepress/**/*.ts",
>     "src/.vitepress/**/*.vue",
>     "packages/**/*.ts",
>     "packages/**/*.js",
>     "packages/**/*.vue",
>     "cypress/**/*.ts",
>     "types/**/*.d.ts",
>     ".eslintrc.js",
>     "postcss.config.js",
>     "tailwind.config.js",
>     "tailwind.animation.js",
>     "vite.config.ts",
>     "vitest.config.ts",
>     "cypress.config.ts",
>     "vitest.setup.ts"
>   ],
>   "exclude": [
>     "node_modules",
>     "coverage",
>     "dist",
>     ".nuxt"
>   ]
> }
> 
```
<img width="610" alt="Screen Shot 2022-12-14 at 15 09 51" src="https://user-images.githubusercontent.com/56768852/207571858-5330476a-487b-456c-9d3e-235372ff1bb9.png">

What should I do to fix that error diagnostic? Thanks

**Comment by chemzqm** [comment]
<img width="480" alt="Screenshot 2022-12-14 at 21 47 56" src="https://user-images.githubusercontent.com/251450/207611841-1d9ae88e-dc17-490a-b4d2-6c96436c37f5.png">
