### ISSUE TITLE
Action "Disable rule for current line/entire file"

### ISSUE THREAD

**Issue by GabrielDuarteM** [neoclide/coc-eslint#14]
`vscode-eslint` provides the following actions:
1. `Disable [rule] for this line`: Adds `// eslint-disable-next-line [rule]` to the line above
1. `Disable [rule] for the entire file`: Adds `/* eslint-disable [rule] */` on the first line of the current file.
![image](https://user-images.githubusercontent.com/7675500/58034404-cf653180-7b26-11e9-9591-447ea5fa3327.png)

I was wondering if there is already a way to do that, and if not, if it would be possible to implement that...

**Comment by chemzqm** [comment]
It's supported by codeAction.
```
" Remap for do codeAction of selected region, ex: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)
```

**Comment by GabrielDuarteM** [comment]
@chemzqm Cool, didn't know about the codeActions, but unfortunately, here it only displays the following options:
![image](https://user-images.githubusercontent.com/7675500/58036685-ff630380-7b2b-11e9-8e5a-e21a502364f7.png)

Not sure if i'm doing something too different, but I added `nmap <silent><leader>. <Plug>(coc-codeaction-selected)`, and the `Disable rule for current line/entire file` are not present on the list, as you can see by the image above

**Comment by chemzqm** [comment]
Not impmented yet.
