### ISSUE TITLE
Extremely slow execution and timeout errors

### ISSUE THREAD

**Issue by sangaline** [neoclide/coc-eslint#16]
Every time that I save a file I get this message:

```
[coc.nvim] eslint will save operation timeout after 0.5s
```

If I save and quit, then I see this printed out in the terminal:

```
Error detected while processing function <lambda>27[1]..<SNR>187_onExit:
line    3:
E684: list index out of range: -1
E15: Invalid expression: a:out[len(a:out) - 1]
```

This is reproducible in even trivial files in empty projects, so I don't think the timeout is due to the complexity of the file being analyzed. Running `:CocCommand eslint.executeAutofix` manually works, but it can take 10-30 seconds on files with less than ten lines of code and no imports. Eslint works fine from the command-line without the same lag.

I'm using version 1.1.2 of the plugin and eslint v5.16.0 on Linux. My coc-eslint config is completely vanilla, I haven't done anything except install the plugin. Please let me know if there's additional information that I can provide which would be helpful.

**Comment by chemzqm** [comment]
Coc.nvim doesn't have code like ` a:out[len(a:out) - 1]` .
I think it's issue with your other vim plugin.

**Comment by chemzqm** [comment]
Use output channel to see what happened https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by sangaline** [comment]
Thanks for the quick reply. It seems like the second error was actually from a prettier plugin, but I still have the coc-eslint timeouts even when I disable that plugin. The output channel shows this after saving:

```
  1 [Info  - 17:21:14] ESLint server running in node v8.11.2
  2 [Info  - 17:21:14] ESLint library loaded from: /tmp/simple-project/node_modules/eslint/lib/api.js
  3 [Error  - 17:21:38] Failed to apply command: eslint.applyAutoFix
```

When I save and quit, I see this now:

```
[coc.nvim] eslint will save operation timeout after 0.5s
```

**Comment by chemzqm** [comment]
You can try `eslint --fix` in your terminal, if it takes more than 0.5s, then it's expected.
Maybe caused by some wired configuration.

**Comment by sangaline** [comment]
Eslint takes longer than 0.5s when I run it from the command-line, but the autoformatting takes significantly less time than it does with the plugin. Isn't the default value of `autoFixOnSave` false? Even when I explicitly set it to false, I still get the timeout error when I save and quit. Is this option possibly not being respected?

**Comment by chemzqm** [comment]
Could be your other plugin fornating your code.

**Comment by sangaline** [comment]
Are you saying that another plugin might be calling `eslint.executeAutofix`? I get the error with

```json
{
  "eslint.autoFix": false,
  "eslint.autoFixOnSave": false,
  "eslint.enable": true,
}
```

but it goes away when I disable the plugin entirely:

```json
{
  "eslint.autoFix": false,
  "eslint.autoFixOnSave": false,
  "eslint.enable": false,
}
```

**Comment by chemzqm** [comment]
It's possible get called in your vim code, `"eslint.autoFixOnSave": false` works as expected for me.

**Comment by alextrastero** [comment]
@sangaline did you manage to solve this? Attached screenshot of my case
![foo](https://user-images.githubusercontent.com/4152819/61366951-e7d59c00-a88a-11e9-8ba4-e567a27fa09f.png)

Happens when I save the file

**Comment by wddwycc** [comment]
I have this issue when used together with coc-prettier

**Comment by tony** [comment]
Removing coc-prettier fixed the lag to me.

**Comment by nomasprime** [comment]
Does anyone know how to change the timeout? Seems to be general issue that 0.5s is too short.

**Comment by kevr** [comment]
This really does not seem like any sort of solution to OP's issue. The answers here were basically to completely disable eslint execution on save, but.. what if we _want_ that? There is no reason eslint should be taking this long to --fix.
