### ISSUE TITLE
[coc.nvim] error: Warning: React version not specified in eslint-plugin-react settings.

### ISSUE THREAD

**Issue by parker789** [neoclide/coc-eslint#19]
When saving .jsx files i get this error when running coc-prettier + coc-eslint. I've tried adding the react version into my .eslintrc, but that did not fix the issue. I can run eslint within VSCode or cli and this doesn't get triggered. Any ideas?

**Comment by chemzqm** [comment]
No idea, checkout verbose output.

**Comment by parker789** [comment]
I'm new to all of this, is there a wiki explaining how to get verbose output from coc.nvim?

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by parker789** [comment]
Awesome, thanks! I'll close this guy
