### ISSUE TITLE
Eslint not running for typescript.tsx files, even though eslint.filetypes is set

### ISSUE THREAD

**Issue by merisbahti** [neoclide/coc-eslint#20]
Hello, 

Eslint isn't running for my `.tsx`-files, the output from `:set filetype` is `filetype=typescript.tsx`,

and my CocConfig is:

```
{
  "eslint.autoFixOnSave": true,
	"eslint.filetypes": ["javascript", "javascriptreact", "typescript", "typescript.tsx", "typescriptreact.tsx", "typescript.jsx", "typescriptreact.tsx"]
}
```

it works for js and ts files.

Any idea what might be wrong? thanks

**Comment by merisbahti** [comment]
Solved it by adding 
```
autocmd BufEnter *.tsx set filetype=typescript
```
to my `nvim.init`

**Comment by chemzqm** [comment]
You're using wrong filetypes, you should use `typescriptreact`

**Comment by merisbahti** [comment]
Thanks, I got it working. What syntax are you using for ts/tsx?

**Comment by shanesmith** [comment]
What was the solution here? I've pieced together from above that it might be `autocmd BufEnter *.tsx set filetype=typescriptreact` but then I get neither coc-eslint nor syntax highlighting. =/

**Comment by shanesmith** [comment]
Oh, I've just figured it out, the autocmd isn't needed, instead here's what I've put in my CocConfig

```
{
  "eslint.filetypes": ["javascript", "javascriptreact", "typescript", "typescriptreact"]
}
```

And here's the relevant line in coc-nvim's documentation: https://github.com/neoclide/coc.nvim/blob/e8e583c8e0baed14cf5dccd89b83dd0103c24d48/doc/coc.txt#L922
