### ISSUE TITLE
How to use local eslint?

### ISSUE THREAD

**Issue by snoblenet** [neoclide/coc-eslint#21]
Is it possible to make `coc-eslint` use the copy of `eslint` at `./node_modules/.bin/eslint`?

It may be a different version to the one installed globally, with different behaviour.

Related: I've experienced some strange autofixes with this plug-in enabled. Can I confirm it reads each project or directory's local `.eslintrc`?

Many thanks.

**Comment by chemzqm** [comment]
It uses local eslint when possible, could be your local eslint can't be resolved.
Checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
