### ISSUE TITLE
coc-eslint occupies 100% CPU when using with eslint 6

### ISSUE THREAD

**Issue by Holi0317** [neoclide/coc-eslint#22]
Node version: v12.7.0
Platform: Linux

When using eslint v6.1.0, coc-eslint is using 100% of cpu resources. This does not occur when the project is using eslint v5.

**Comment by ohjames** [comment]
I am using eslint 6.4 on Linux here and am not seeing this.

**Comment by Holi0317** [comment]
Oops. Sorry I forgot to report to this issue.

That was a weird issue. I have remove node_modules and run `yarn install` again and the problem was solved.

Perhaps that was a weird linking issue.
