### ISSUE TITLE
Errors don't update on file change

### ISSUE THREAD

**Issue by Dammic** [neoclide/coc-eslint#25]
Hello,

I have a problem with the package. When I open a jsx (or js) file for the first time, it shows me errors (even when I hover on them, the message at the bottom shows me what is the problem). As soon as I edit the file in any way, the errors stop refreshing and the new errors are not shown anymore. What's more, when I hover over the previous problems, I don't see the message in the message line (the problem looks like on the screen).

I've tried to install purely only coc-vim and then coc-eslint. I've tried to run without any plugins and configuration except for coc-vim and the problem is still there. I've tried to run it on ubuntu and on macos, tried different nvim versions, tried different node versions, tried different projects and the problem doesn't disappear.
It works fine with ALE.

I've also tried to debug it and see if :CocInfo or any other command I could think of returns any error, but there is nothing there.

Interestingly enough, if the file I open has wrong syntax (ex. declared the variable twice), after I remove the variable it refreshes the linting. Also when I do :CocRestart, it refreshes the errors.

(On screenshot: it's an error that the variable is unused, I've just added the 'xxxx' variable that doesn't get linted)
I'm using the latest available version of coc-eslint

![Screenshot 2019-08-29 at 08 57 26](https://user-images.githubusercontent.com/18100361/63917520-1b374900-ca3b-11e9-886b-529ae83d73eb.png)

Output from :CocInfo after going into file, adding the line and saving it:
![ksnip_20190829-091751](https://user-images.githubusercontent.com/18100361/63918911-f7c1cd80-ca3d-11e9-8fa2-3ef7b4aa22ed.png)

Link to my configs:
https://gitlab.com/Dammic/dotfiles

Could you point me to an issue that could be there (or point me to any diagnostics that could help me debug the problem)? Thanks in advance!

**Comment by James868** [comment]
I also have the same problem.
Using nvim 0.3.8, node v12.9.0, and coc.nvim 0.0.74.

Interestingly, this problem only occurs when I am working on a local project, no problem with github project.

**Comment by chemzqm** [comment]
It doesn't refresh on insert mode, it's feature.

**Comment by Dammic** [comment]
It doesn't work for me when saving file either (outside of insert mode). Only restarting coc client works.

**Comment by chemzqm** [comment]
Can't reproduce, please provide verbose output https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by Dammic** [comment]
@chemzqm I've found out what might be a problem for me.
I'm using ctrl + c combination to exit insert mode. When I've used esc, it's all working fine all out a sudden.

**Comment by chemzqm** [comment]
@Dammic Thanks for reporting, vim doesn't report InsertLeave when exist insert mode by `ctrl-c`
