### ISSUE TITLE
LanguageClient not starting for vue files

### ISSUE THREAD

**Issue by spetex** [neoclide/coc-eslint#27]
Hello,

I have been trying to run eslint for `.vue` files with `vue` filetype. Works perfectly fine for coc-vetur, coc-prettier however not for coc-eslint. It wont start even though I have added vue into the eslint.filetypes array. I can switch to filetype javascript or typescript to actually test it out (it starts and lints) but that breaks my other plugins as expected.

Is vue supported?

**Comment by chemzqm** [comment]
You have to use `eslint.filetypes` configuration for filetypes other than javascript.

**Comment by spetex** [comment]
>  have added vue into the eslint.filetypes array.

I have did that.

**Comment by npearson72** [comment]
@chemzqm I am also having this issue:

Here are my coc-settings:

```
{
  "diagnostic.errorSign": "",
  "diagnostic.warningSign": "",
  "eslint.run": "onSave",
  "eslint.filetypes": ["vue", "js"],
  "prettier.trailingComma": "none",
  "prettier.singleQuote": true,
  "prettier.eslintIntegration": true,
  "prettier.bracketSpacing": false,
  "prettier.arrowParens": "avoid",
  "prettier.jsxBracketSameLine": true,
  "suggest.snippetIndicator": " ",
  "vetur.validation.template": false
}
```

I have the following extensions:

```
let g:coc_global_extensions=[
      \ 'coc-css',
      \ 'coc-elixir',
      \ 'coc-eslint',
      \ 'coc-html',
      \ 'coc-json',
      \ 'coc-prettier',
      \ 'coc-solargraph',
      \ 'coc-tsserver',
      \ 'coc-snippets',
      \ 'coc-vetur'
      \]

```

Works great in `js` files, but in `vue` files I get no linting unless I install `eslint` and and `eslint-plugin-vue` as a dev dependency in my project.

What's the point of the server if I still need to install the dependencies per project?

**Comment by eulertour** [comment]
@chemzqm I'm fine with @npearson72's answer, but can it be mentioned somewhere more obvious for people using vue?
