### ISSUE TITLE
Missing semicolon cannot be fixed with code action

### ISSUE THREAD

**Issue by FallenWarrior2k** [neoclide/coc-eslint#28]
I'm using eslint-plugin-prettier, with `"semi": true` in my `.prettierrc`.
coc-eslint correctly marks lines with a missing semicolon as erroneous in the gutter, but no visible part of the line actually gets associated with the error, and as such, both `coc-codeaction` and `coc-codeaction-selected` don't show an option to fix it.
Instead, I have to trigger the autofix via `:CocCommand eslint.executeAutofix`.
![image](https://user-images.githubusercontent.com/20320149/66703100-40dc9100-ed0f-11e9-9652-c680a9569a81.png)
![image](https://user-images.githubusercontent.com/20320149/66703108-55208e00-ed0f-11e9-9cb0-21fe04d91c5b.png)

I assumed this was related to the error column being past the end of the line, so I tried adding an extra space at the end of the line.
The space gets marked as an error and can hence be fixed via code action.
![image](https://user-images.githubusercontent.com/20320149/66703175-f6a7df80-ed0f-11e9-8be9-27dadbfc6444.png)

**Comment by FallenWarrior2k** [comment]
While `set virtualedit=onemore` makes the floating window with the error message show up when one character past the end, the fix option still does not show up in the list of code actions when triggering `<Plug>(coc-codeaction)` in that state.

**Comment by chemzqm** [comment]
There's no fix option for this, I suggest use vim's global replace for it

**Comment by FallenWarrior2k** [comment]
Alright, thank you.
