### ISSUE TITLE
langserver failure

### ISSUE THREAD

**Issue by burgessa23** [neoclide/coc-eslint#3]
Hi, since yesterday I've been getting the following error:

```sh
[coc.nvim] server eslint langserver failed to start: undefined
```

no changes to configs, just did `:CocUpdate` I've tried un/re installing
Any ideas?

**Comment by chemzqm** [comment]
Please provide result from `:CocInfo`

**Comment by chemzqm** [comment]
Have no idea of what happened, consider build coc.nvim from source: https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#install-plugin-cocnvim

I've improved the error message handling.

**Comment by chemzqm** [comment]
I got the reason, there's a script used by binary release that is removed.

I've added the file back.

To avoid such kind of break, use tag when using binary realease of coc.nvim, like:

``` vim
Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install()}}
```

**Comment by burgessa23** [comment]
build from source fixed it, thanks
