### ISSUE TITLE
Does coc-eslint support ts files ?

### ISSUE THREAD

**Issue by LifeIsStrange** [neoclide/coc-eslint#30]
TSlint is being deprecated and eslint is replacing it.
Does coc-eslint supports and scan .ts files ?

**Comment by fannheyward** [comment]
Yes, add ts to `eslint.filetypes` to enable for ts.

**Comment by LifeIsStrange** [comment]
@fannheyward Thank you for the fast response, but I strongly believe that it should be added by default.

**Comment by LifeIsStrange** [comment]
Also how does this relate to https://github.com/typescript-eslint/typescript-eslint ?

**Comment by chemzqm** [comment]
> Also how does this relate to https://github.com/typescript-eslint/typescript-eslint ?

Nothing.

**Comment by nathanshelly** [comment]
@LifeIsStrange the monorepo you linked to explains how to configure your `.eslintrc.json` ([here's an example of mine](https://github.com/nathanshelly/wut_client/blob/37c9b60789d203f7f1ef6accaa1a459b446ef703/.eslintrc.json)). `coc-eslint` should work regardless of whatever configuration (whether it's typescript or javascript) you have.

**Comment by LifeIsStrange** [comment]
@nathanshelly thank you! (but your example is a deadlink (404 error))

You answered all my questions, I guess this issue can be closed once you decide if you add ts to eslint.filetypes by default.

**Comment by nathanshelly** [comment]
> @nathanshelly thank you! (but your example is a deadlink (404 error))

@LifeIsStrange whoops my bad, didn't think about it being a private repo  🤦‍♂, glad all your questions are answered 😄 

Also would like to express my agreement with adding `ts` to `eslint.filetypes` by default, definitely think it would be a nicer default experience.
