### ISSUE TITLE
coc-eslint doesn't start for TS files in some cases

### ISSUE THREAD

**Issue by jason0x43** [neoclide/coc-eslint#33]
I would like to enable coc-eslint for TS files on a project-by-project basis. If I add the TS filetypes to `eslint.filetypes` in the global coc config, coc-eslint is always started when I edit a TS file. However, if I only add the TS types to `eslint.filetypes` in a project-local coc config, eslint is only started if I start vim with a file. For example, if I start vim with just `vi` and then edit a JS file with `:e src/file.js`, coc-eslint isn't started. However, if I open vim with `vi src/file.js`, `coc-eslint` is started.

How can I get eslint to start for TS files, but only for certain projects?

**Comment by jason0x43** [comment]
Ah, never mind. The solution seems to be to leave the filetypes in the global coc config, but disable coc-eslint by default in the global config (`"eslint.enabled": false`), and only enable it on a project-by-project basis.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file
