### ISSUE TITLE
Disable eslint on project basis

### ISSUE THREAD

**Issue by andys8** [neoclide/coc-eslint#34]
I've projects using eslint and others using tslint. For the project that isn't using tslint there is a warning that eslint can't be started and after installing it globally it says "no eslint configuration found". But it shouldn't be executed for this projects.

Would it be an option to disable the plugin for projects that have no configuration instead?

**Comment by chemzqm** [comment]
Checkout https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file or create eslint config file in your $HOME

**Comment by andys8** [comment]
Thanks for the reply.

Thought about those solutions:
* global eslint won't work, because projects are far too different (node/js/ts/frameworks).
* disabling in project would work, but depends on modifying a project even if it's not owned

**Comment by andys8** [comment]
How about an option `ignoreProjectsWithoutEslintConfig`/`disableProjectsWirhoutEslintConfig`? :)

**Comment by chemzqm** [comment]
No, global eslint config file could work as default configuration file.

**Comment by andys8** [comment]
Yeah, I understand. I think it won't work for my case. E.g. it's a minimal eslint config file. Then opening a typescript based project without eslint file will fail, because its content can't be parsed. This eslint would basically have to match any project (ts, js, browser, node, react, vue).

**Comment by sethfowler** [comment]
I ran into the same problem. +1 on adding an option to ignore projects without an ESLint configuration file. A global default ESLint configuration really just won't work; like @andys8 said, you need different configurations for TypeScript vs JavaScript and node projects vs browser projects.

**Comment by chemzqm** [comment]
eslint doesn't provide an API for resolve configuration file, so you have to use `"eslint.enable": false` in your `.vim/coc-settings.json` inside project folder.

**Comment by davidosomething** [comment]
maybe something like
```
  autocmd BufNewFile,BufReadPre,BufEnter
        \ */myproject/*.{js,jsx,ts,tsx}
        \   call coc#config('eslint.enable', v:false)
  autocmd BufLeave
        \   call coc#config('eslint.enable', v:true)
```
