### ISSUE TITLE
Unable to resolve plugins

### ISSUE THREAD

**Issue by monsonjeremy** [neoclide/coc-eslint#35]
I'm finally making the jump over to nvim and i'm having some issues getting set up. I ran `:healthcheck` and everything is green checkmarked, however I can't get coc-eslint to work. 

For example if I open up `./App/src/file.js` I get the following error inside the coc-eslint `:CocList output -> eslint` output:

    [Info  - 7:42:13 AM] ESLint server running in node v12.12.0
    [Info  - 7:42:13 AM] ESLint library loaded from: /App/node_modules/eslint/lib/api.js
    [Error  - 7:42:13 AM] Failed to load plugin 'jsx-a11y' declared in 'homepage/.eslintrc': Cannot find module 'eslint-plugin-jsx-a11y'
    Require stack: /App/__placeholder__.js
    Happened while validating /App/src/file.js
    This can happen for a couple of reasons:
      1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
      2. If ESLint is installed globally, then make sure 'eslint-plugin-jsx-a11y' is installed globally as well.
      3. If ESLint is installed locally, then 'eslint-plugin-jsx-a11y' isn't installed correctly.
    
    Consider running eslint --debug /App/src/file.js from
    a terminal to obtain a trace about the configuration files used.

However I know there is no issue with the plugin missing because I ran npm install, and if I open the same file in VSCode from the same root directory it works just fine and is able to lint.

I'm also able to successfully lint by running:

    eslint --debug /App/src/file.js

Anyone have any ideas why it would not be able to load plugins?

**Comment by monsonjeremy** [comment]
It looks like this issue is related to `eslint@6`. When I downgrade, I am able to run `coc-eslint` properly.

**Comment by chemzqm** [comment]
I think you need upgrade your eslintrc.

**Comment by monsonjeremy** [comment]
@chemzqm My `eslintrc` is totally fine, i'll paste it here if you're curious:
```
{
  "extends": ["airbnb", "prettier"],
  "parser": "babel-eslint",
  "env": {
    "node": true,
    "es6": true,
    "browser": true
  },
  "plugins": [
    "react",
    "prettier",
    "react-hooks"
  ],
  "rules": {
    "prettier/prettier": "error",
    "react/sort-comp": 0,
    "react-hooks/rules-of-hooks": "error", // Checks rules of Hooks
    "react-hooks/exhaustive-deps": "error" // Checks effect dependencies
  }
}
```

If I run `eslint` from the command line from the same working directory I have no issues. Also once I downgraded to `eslint@5` it worked fine. I really don't think it's an issue with my `eslintrc` file.

**Comment by Gee19** [comment]
Out of curiousity, what is the output of `cat package.json | grep 'eslint'`?

**Comment by Boelensman1** [comment]
I'm having the exact same problem, same plugin even. Also using a very similar eslintrc.

This is the output of `cat package.json | grep 'eslint'`

    "lint": "npx eslint . && npx prettier --check .",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.1.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.20.0",

jsx-a11y is in fact installed and if I run eslint manually it works just fine

**Comment by Boelensman1** [comment]
Looking at the trace it seems to set the wrong workspace folder:
```
[Trace - 2:47:08 PM] Sending response 'workspace/configuration - (1)'. Processing request took 1ms
Result: [
    {
        "packageManager": "npm",
        "quiet": false,
        "validate": true,
        "autoFix": true,
        "autoFixOnSave": true,
        "options": {},
        "run": "onSave",
        "workspaceFolder": {
            "uri": "file:///files/appeal",
            "name": "appeal"
        },
        "codeAction": {
            "disableRuleComment": {
                "enable": true,
                "location": "separateLine"
            },
            "showDocumentation": {
                "enable": true
            }
        }
    }
]
```
The workspace should actually be appeal/project. The repository is appeal but the package.json and .eslintrc are located in appeal/project.

**Comment by nomasprime** [comment]
Issue for me to. Did anyone get this working and how?
