### ISSUE TITLE
Not respecting "onSave" setting

### ISSUE THREAD

**Issue by roginfarrer** [neoclide/coc-eslint#37]
## What I did:

```json
{
  "eslint.run": "onSave"
}
```

## What I expected to happen

I expected no new lint warnings until I save the file.

## What actually happened

Instead of waiting until I save, the file is linted the second I leave INSERT mode.

My project as a lint rule for ensuring you run prettier. The rule has the unfortunate habit of making the entire file an error. This would usually not be an issue, since I have format on save enabled, in addition to only running ESLint on save (see above rule). But I'm finding that instead, when I write something in insert mode that's not formatted correctly, the file is linted when I exit insert mode, even though the file has not been saved.

**Comment by chemzqm** [comment]
I can't reproduce.

**Comment by roginfarrer** [comment]
It's a bit hard to share how to reproduce, since the rule that creates the error is a custom rule, but here's a gif:

![](https://p91.f3.n0.cdn.getcloudapp.com/items/xQuvrxZ7/Screen+Recording+2019-11-22+at+08.49+AM.gif)

**Comment by chemzqm** [comment]
Could be from other vim plugin, try minimal vimrc.
