### ISSUE TITLE
Lightline support

### ISSUE THREAD

**Issue by maharjanaman** [neoclide/coc-eslint#38]
Is there a way to show warnings and errors in [lightline](https://github.com/itchyny/lightline.vim)?

**Comment by fannheyward** [comment]
`:h coc-status-lightline`

**Comment by maharjanaman** [comment]
@fannheyward thanks,
<img width="274" alt="Screen Shot 2019-12-02 at 12 55 11" src="https://user-images.githubusercontent.com/14164484/69937499-1505ac80-1503-11ea-8ae3-dd742dce733f.png">
Is there a way to add space between?

**Comment by fannheyward** [comment]
You can write a function to format it as you want, check `:h coc-status-manual`, then use it in `component_function`, something like this: https://github.com/itchyny/lightline.vim#can-i-display-the-plugin-name-at-the-mode-component

**Comment by maharjanaman** [comment]
Oh ok, thanks.
