### ISSUE TITLE
Add ability to show eslint errors in quickfix/location list

### ISSUE THREAD

**Issue by jssee** [neoclide/coc-eslint#40]
It would be great to be able to choose whether or not the user wants to have diagnostics from this extension into the quickfix/location list to leverage some of the features they provide

**Comment by anshulguleria** [comment]
Agree to @jssee . I liked this feature in ALE and I miss this a lot in coc-eslint.

It would definitely help to have a list of all issues.

**Comment by chemzqm** [comment]
No, you can write function to load diagnostics from coc.nvim then use quickfix or location list to show them (read doc of coc.nvim), the reason is vim use shared quickfix and location list which is less featured than CocList.

**Comment by anshulguleria** [comment]
Thanks.

Could you point me to that documentation?

**Comment by alexandermckay** [comment]
I would also like to see where the documentation explains this feature.

**Comment by chemzqm** [comment]
`:h :CocDiagnostics`
