### ISSUE TITLE
Error when opening .eslintrc.js

### ISSUE THREAD

**Issue by alexseitsinger** [neoclide/coc-eslint#42]
When I open my .eslintrc.js or similar file with coc-tsserver, coc-prettier & coc-eslint I receive a continuous error in my statusline:

> [coc.nvim] error: UnhandledRejection: Range#create called with invalid arguments[null, -1, null, 0]

It appears this error is being caused by DiagnosticBuffer.fixRange, but I am unable to figure out what the source of the problem is or how to resolve it. I have tried various things to no avail.

All that I have been able to figure out is that the error is likely coming from coc-eslint, since removing this makes the error disappear.

Any suggestions?

Thanks

**Comment by chemzqm** [comment]
Fixed on latest release of coc.nvim.
