### ISSUE TITLE
editing file before full load breaks eslint

### ISSUE THREAD

**Issue by MeisterTea** [neoclide/coc-eslint#44]
If I open a js file and start editing right away, I won't have any eslint error as long as my file is open.
I have to wait like 3 seconds and only then I can edit my file and eslint errors are visible.

Can this be fixed?

I would also like to know if it's possible to use eslint_d in coc_eslint?

**Comment by chemzqm** [comment]
> Can this be fixed?

Can't reproduce.

> I would also like to know if it's possible to use eslint_d in coc_eslint?

No.
