### ISSUE TITLE
Does not resolve eslint library for yarn2 projects

### ISSUE THREAD

**Issue by darce2** [neoclide/coc-eslint#46]
When using yarn2 for a project I am getting an error saying `Failed to load the ESLint library for the document ...`. With yarn2 pnp is enabled so there is not a node_modules folder and thus eslint cannot be resolved from the workspace.  

Info Output Below:
```## versions

vim version: NVIM v0.4.3
node version: v12.15.0
coc.nvim version: 0.0.74-6700e7468d
term: xterm-256color
platform: linux

## Messages
[coc.nvim] Failed to load the ESLint library for the document /home/arlen/workspace/node/marianos_clipper/index.js
## Output channel: prettier


## Output channel: tsserver

[Info  - 3:45:46 PM] Forking TSServer
PATH: /home/arlen/.nvm/versions/node/v12.15.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/arlen/Dotfiles/functions:/home/arlen/.gem/ruby/2.7.0/bin:/home/arlen/Applications:/home/arlen/Dotfiles/functions:/home/arlen/.gem/ruby/2.7.0/bin:/home/arlen/Applications 
[Info  - 3:45:46 PM] Started TSServer
{
  "path": "/home/arlen/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.7.3",
    "version": "3.7.3"
  }
}

## Output channel: eslint

[Info  - 3:45:46 PM] ESLint server running in node v12.15.0```

**Comment by fannheyward** [comment]
From https://next.yarnpkg.com/advanced/pnpify I found a fallback solution:

1. `yarn add @yarnpkg/pnpify` add pnpify to your project.
2. `alias eslint=yarn pnpify eslint` in your project

Can you test whether this works?

**Comment by fannheyward** [comment]
Or https://master--yarn2.netlify.com/advanced/editor-sdks:

1. `yarn add @yarnpkg/pnpify` in your project
2. `yarn pnpify --sdk`
3. `"eslint.nodePath": "./.vscode/pnpify/"` to `coc-settings.json`

I don't use yarn2 yet, just from docs to find this two solutions. Hope you can test both and give feedbacks.

**Comment by darce2** [comment]
@fannheyward I am able to 
```yarn eslint``` without an issue.
Installing the sdk and pointing the nodePath worked! 

Thanks!

Is this the expected behavior or is there work to be done to address this without needing to add a settings file for projects using pnp?

**Comment by fannheyward** [comment]
For yarn2 project:

1. `yarn add @yarnpkg/pnpify` to you project
2. `yarn pnpify --sdk`

`coc-eslint` will resolve ESLint automatic after #48 merged.

**Comment by Nate-Wilkins** [comment]
@fannheyward are there ways to debug issues for loading coc-eslint?
