### ISSUE TITLE
How to use coc-eslint with yarn2 project?

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc-eslint#49]
`coc-eslint` already support yarn2 project, but you need do following setup:

1. `yarn add @yarnpkg/pnpify` in your project, this will add pnpify to your project.
2. `yarn pnpify --sdk`, this will generate directory `.vscode/pnpify` that contains `eslint`

Now `coc-eslint` can load ESLint automatically.

**Comment by chemzqm** [comment]
Need upgrade to latest vscode-eslint https://github.com/microsoft/vscode-eslint

**Comment by fannheyward** [comment]
This is not an issue, but notes for yarn2 project usage. `coc-eslint` already support yarn2 on #48

**Comment by dzintars** [comment]
Tried earlier to follow up these instructions but without any success.
Yesterday made a clean Yarn setup - 1.23 accessible globally and Berry locally for project. In VS Code works as expected without any issues, but in nvim with CoC still no luck.
Today ended up with setting up [LanguageClient](https://github.com/autozimu/LanguageClient-neovim) +  [Server](https://github.com/theia-ide/typescript-language-server) and got it working, but i think then i should remove CoC.
I am bad at providing meaningful feedback, as I have no idea how all this crazy stuff is tied together and why it is made so complicated for newbies (no precise/complete documentation). All this thing rarely works out of the box. And i have no idea, why ESLint started to work only after installing TypeScript language server. Later will try to clean up system again and to start from scratch.
