### ISSUE TITLE
Disable particular lint rules

### ISSUE THREAD

**Issue by tylerjdurden** [neoclide/coc-eslint#50]
There doesn't appear to be a way to disable particular lint rules. I don't want to disable the rule in eslint itself, as I want eslint to still check for / flag the rule at commit time, I just want it to be quiet about a particular rule in my editor.

**Comment by chemzqm** [comment]
Checkout document of eslint

**Comment by nseptier** [comment]
@tylerjdurden Did you happen to find a solution without having to alter the .eslintrc file?
