### ISSUE TITLE
eslint-react-hooks - code action is missing

### ISSUE THREAD

**Issue by vitpekarek** [neoclide/coc-eslint#55]
Hi,
I miss code action from eslint-react-hooks.
There is action in vs code named 'Fix this react-hooks/exhaustive-deps problem' that fix (add/remove) dependencies (like testProp in useMemo hook).

Minimal test code:
```tsx
import * as React from "react";
import { useMemo } from "react";

export const FComponent: React.FC<{}> = ({ testProp }) => {
    const test = useMemo(() => {
        if (testProp) return "test";
        return "-";
    }, [testProp]);

    return <div>{test}</div>;
};
```

Is this some kind of bug or just missing functionality?
Thanks

**Comment by vitpekarek** [comment]
It seems that it is working now... maybe my mistake was that I didn't have neovim npm package installed....

**Comment by Dema** [comment]
I'm having the same issue. `neovim` npm package is installed. It's interesting that only the action for this rule is not shown. Things like "prefer-const" and other are working fine.

**Comment by conradob** [comment]
> I'm having the same issue. `neovim` npm package is installed. It's interesting that only the action for this rule is not shown. Things like "prefer-const" and other are working fine.

I also did manage to make this work, let me know if you find a solution, please :v: .

**Comment by Dema** [comment]
@conradob They removed autofix for this and then restored it behind the scary flag:)
```
    "react-hooks/exhaustive-deps": [
      "error",
      { enableDangerousAutofixThisMayCauseInfiniteLoops: true },
    ],
```
