### ISSUE TITLE
Fix using `<Plug>(coc-format)`

### ISSUE THREAD

**Issue by chmanie** [neoclide/coc-eslint#57]
I'm trying to use the same key-binding I set up with this plugin. I also set

```
javascript.format.enable: false,
typescript.format.enable: false,
```

to disable the formatting of the tsserver. My goal is to use the same key-binding for every language I'm writing. That should be possible, right? Am I missing something?

My current workaround is to use `ftplugin` files and map the key-binding separately.

**Comment by chemzqm** [comment]
eslint doesn't have format feature at all.

**Comment by chmanie** [comment]
Hm, I'd actually argue against it. I think the potential formatting features of eslint outweigh the capabilities of tsserver (which supports formatting) by far, especially when used with [eslint-prettier](https://github.com/prettier/prettier-eslint).

Maybe we have a different definition of what "formatting" entails but at least the eslint-prettier plugin talks about formatting a lot:

> The fix feature of eslint is pretty great and can auto-format/fix much of your code according to your ESLint config.

The ftplugin solution works fine for me though I was hoping for a more general solution.

**Comment by chemzqm** [comment]
Prettier does format, not eslint.

**Comment by chmanie** [comment]
Oh, I just found this: https://github.com/neoclide/coc-prettier#prettiereslintintegration-default-false---javascript-and-typescript-only

I didn't know that the prettier plugin could work with prettier-eslint. Never mind then!
