### ISSUE TITLE
Unclear Configuration Documentation

### ISSUE THREAD

**Issue by stephen-smith** [neoclide/coc-eslint#58]
The individual options and valid values is well-described at https://github.com/neoclide/coc-eslint#configuration-options

Unfortunately, this doesn't tell me what file (or other method?) is used to actually specify the configuration.  I'm assuming `:CocConfig` and then just add them in the top level object?  Or maybe package.json in the "eslintConfig" object?  Also, the naming sort of implies I might be able to group options together like `"eslint" { "quiet": true, "autoFixOnSave": true }`, but that's not clear.

I'm relatively new to using coc, so it's probably just my ignorance, but just mentioning `:CocConfig` would help.  If the dot-separated names do allow grouping configurations, one example with things group and one example with them no grouped would also be helpful.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file

**Comment by stephen-smith** [comment]
Yeah, but it's not clear your configurations go in `:CocConfig`, you don't mention it at all.

**Comment by gaving** [comment]
Agree with this, completely confused hence searching the issues.
