### ISSUE TITLE
Problems Loading @vue/eslint-config-typescript@4.0.0

### ISSUE THREAD

**Issue by stephen-smith** [neoclide/coc-eslint#59]
I have it listed in my devDependencies in package.json.

It is currently installed.  (Shows in `npm list`)

`vue-cli-service lint` and `npm run lint` can find it.

coc-eslint doesn't seem to find it, even though it is using my local ESLint.

```
## Output channel: eslint

[Info  - 11:09:52 PM] ESLint server running in node v10.21.0
[Info  - 11:09:53 PM] ESLint library loaded from: /home/bss/.npm/lib/node_modules/eslint/lib/api.js
[Error  - 11:09:53 PM] Cannot find module '@vue/eslint-config-typescript' Referenced from: /home/bss/git/vue-webpack-ts-lambda/package.json
```

**Comment by chemzqm** [comment]
`/home/bss/.npm/lib/node_modules/eslint/lib/api.js` it's not your local eslint, you have to install eslint in your project.
