### ISSUE TITLE
Issues when installing via CocInstall <github link>

### ISSUE THREAD

**Issue by uglywizkid** [neoclide/coc-eslint#60]
Because I am using a private npm repository and CocInstall "package name" does not work, I am using CocInstall "github link" instead. This worked fine for coc-tsserver and coc-prettier. But with coc-eslint unfortunately it does not work as nice.

After installing with CocInstall https://github.com/neoclide/coc-eslint and after a CocRestart, the following error message occurs:
```
[coc.nvim] Unable to load global extension at .config/coc/extensions/node_modules/coc-eslint: main file lib/index.js not found, you may need to build the project.
```

Ok, I can fix that, I thought. I changed directory to .config/coc/extensions/node_modules/coc-eslint and entered a simple npm install. Then webpack reports the following error:
```
> coc-eslint@1.2.7 build /home/tgiess/.config/coc/extensions/node_modules/coc-eslint
> webpack

Hash: af29c38ae96c8c079986
Version: webpack 4.43.0
Time: 89ms
Built at: 19/06/2020 11:46:27
    Asset      Size  Chunks             Chunk Names
 index.js  4.02 KiB       0  [emitted]  index
server.js  4.22 KiB       1  [emitted]  server
Entrypoint index = index.js
Entrypoint server = server.js
[0] ./src/index.ts 398 bytes {0} [built] [failed] [1 error]
[1] ./server/index.ts 591 bytes {1} [built] [failed] [1 error]

ERROR in ./src/index.ts 10:10
Module parse failed: Unexpected token (10:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| const defaultLanguages = ['javascript', 'javascriptreact', 'typescript', 'typescriptreact']
> namespace Is {
|   const toString = Object.prototype.toString
| 

ERROR in ./server/index.ts 14:8
Module parse failed: Unexpected token (14:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { getAllFixEdits, executeInWorkspaceDirectory, getFilePath, isUNC, resolveModule } from './util'
| import { TextDocument } from 'vscode-languageserver-textdocument'
> declare var __webpack_require__: any
| declare var __non_webpack_require__: any
| const requireFunc = typeof __webpack_require__ === "function" ? __non_webpack_require__ : require

```

That is strange, I thought. The webpack.config.js looks fine. ts-loader is configured. Why does this not work? Then I thought: Maybe webpack has an issue with nested node_modules folders, because node_modules is explicitly excluded in the webpack.config.js file. So I copied the whole coc-eslint directory to my home folder and there npm install just runs fine.

I do not really know how to fix this issue, but it would be very nice, if it just works when installing via CocInstall https://github.com/neoclide/coc-eslint.

**Comment by chemzqm** [comment]
Hm, you should not use url for install coc extension that written with typescript.
