### ISSUE TITLE
Triggering format while one in progress creates invalid results

### ISSUE THREAD

**Issue by osdiab** [neoclide/coc-eslint#61]
I was getting pretty confused why my code kept ending up with invalid code blocks until I realized whats happening: I have auto format on save on with `coc-eslint` and configured `eslint-config-prettier` to format my code. The codebase is pretty big and complex so one lint pass on a file can take a few seconds to complete. If I save to trigger a lint, and then save again while it's linting, it seems to update the buffer twice, in a way that creates duplicated code blocks. 

I haven't thoroughly debugged it to ensure this is the problem, but it seems very likely since I don't have any other code formatting vim plugins that would act this way I believe; perhaps this project ought to wait for outstanding formatting jobs to be complete before trying to do another, or cancel/unsubscribe from the previous job if another one has been triggered.

**Comment by chemzqm** [comment]
Looks like your have `eslint.autoFixOnSave` and `coc.preferences.formatOnSaveFiletypes` to true at the same time.

**Comment by chemzqm** [comment]
Can't reproduce with latest coc-eslint
