### ISSUE TITLE
No error or warning description

### ISSUE THREAD

**Issue by JangoCG** [neoclide/coc-eslint#63]
I just started using coc-eslint, however I get no error or warning descriptions. I get error or warning indicators on the left, but when I move to cursor to the line i get no description

![image](https://user-images.githubusercontent.com/19599060/85688596-2c3ffd80-b6d2-11ea-947e-d7a603536820.png)

**Steps to Reproduce this issue:**
1. Install CoC
2. Install Coc-eslint
3. open a js file with VIM and safe
4. move cursor to line with a warning or error message.

**Comment by chemzqm** [comment]
Try minimal vimrc.
