### ISSUE TITLE
how to not use eslintrc

### ISSUE THREAD

**Issue by mirsella** [neoclide/coc-eslint#66]
hello

every time I open nvim I got this error message because I don't have a .eslintrc in my home dir, and I don't want to create one because I don't want to pollute it with another file.
`[coc.nvim] No ESLint configuration (e.g .eslintrc) found for file: /home/mirsella/a.js`

so is it possible to :
1) use the options --no-eslintrc to eslint ?
or 
2) use another path than my home dir to create an empty .eslintrc

thanks

**Comment by mirsella** [comment]
didn't see the config options, i'm dumb

**Comment by sebastiangelotte** [comment]
> didn't see the config options, i'm dumb

Could you perhaps update with your solution for future googlers like myself? :)

**Comment by mirsella** [comment]
thanks, I feel less dumbs now.

I didn't see the config options in the readme, it appear that it's invisible for us at the first look.
it wasn't clear first but thoses config have to be in coc-settings.json file, which is coc.nvim config file, probably in your .config/nvim or /vim folder.

in it I have the configuration options to change the .eslitnrc.json to a empty json file with just `{}` in it.

don't hesitate to ask questions, I'm French, on mobile, and I have to go so I know my explanation
