### ISSUE TITLE
eslint.autoFixOnSave should not automatically disable when no eslint configuration is found

### ISSUE THREAD

**Issue by miki725** [neoclide/coc-eslint#68]
I work on some projects which have eslint configuration and it is very useful to enable autofix as by default vim-coc configuration. However sometimes I open miscellaneous js files which do not have eslint configuration. coc-eslit then shows this error on file save:

```
[coc.nvim] Error on willSaveWaitUntil: Error: Request textDocument/willSaveWaitUntil failed with message: No ESLint configuration found in {path}
```

Ideally if no configuration is found, autosave should silently proceed unless there is configuration in which case actually apply the fixes.

**Comment by chemzqm** [comment]
It's error from eslint, it requires configuration to work.
