### ISSUE TITLE
eslint / tsserver errors won't disappear after being fixed

### ISSUE THREAD

**Issue by ianchanning** [neoclide/coc-eslint#72]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.4
node version: v12.18.3
coc.nvim version: 0.0.78-fc983ce6dd
term: xterm-256color
platform: linux

## Output channel: eslint

[Info  - 14:24:59] ESLint server running in node v12.18.3
[Info  - 14:25:00] ESLint library loaded from: /home/channi16/imec/innovatrix/images/front/node_modules/eslint/lib/api.js
[Info  - 15:11:19] ESLint library loaded from: /home/channi16/imec/innovatrix/images/api/node_modules/eslint/lib/api.js
```

## Describe the bug

The bug is hard to reproduce because it is only temporary. But it happens multiple times per day.

It happens with both coc-eslint and coc-tsserver so I don't believe that it is an issue with those individually.

What happens is that I get a linting error message that shows a warning.

I then fix that error but the warning does not go away.

So I am left with a warning that I can't clear. I can run `:CocRestart` to clear the warning, but it seems like this is a bug.

## Reproduce the bug

I can't reproduce this directly - it only happens on occasion about twice per day.

I have removed the coc-tsserver plugin to make sure it is nothing to do with coc-tsserver and coc-eslint conflicting.

## Screenshots (optional)

You can see here that the eslint warning is pointing to line 661 where the variable used to be - but I have since move the variable a few lines up and fixed the warning.

![Screenshot from 2020-09-08 19-37-04](https://user-images.githubusercontent.com/233318/92510898-d842b080-f20c-11ea-8cab-6fbb3f716c75.png)

**Comment by ianchanning** [comment]
I'm getting these crashes more an more. It happens every couple of hours. I'll try and recreate a minimal version

**Comment by BerkeleyTrue** [comment]
I'm getting the same issue. I can fix the issue but coc still reports the issue (eslint in my case). I can re-read the file `:e` and it will update the eslint issues.

**Comment by Prakhil-tp** [comment]
I'm also getting the same issue. The error indication persists after the fix. Mostly happens when working with React files. 
The "workspace.showOutput" is clean with no errors.

**Comment by ianchanning** [comment]
> Happens on unsaved buffer, but not exists file.

So this is not exactly what I see - but I think it's something close.

I believe the problems with Coc started after I turned on the eslint 'fix on save' option:

```json
  "eslint.autoFixOnSave": true,
```

So in my case the file definitely exists, it's a relatively long (almost always 200+ lines) React JSX file. But I see that sometimes the fix on save doesn't properly work. After I save the file eslint will modify the file and I will need to save it again.

For the moment I have turned this off and I will see if I experience any more problems. If I don't have any more problems for a while, then I'll try turning the fix on save back on with a minimal config.

**Comment by ianchanning** [comment]
Even with autoFixOnSave turned off it still crashes:

![Screenshot from 2020-09-14 22-53-54](https://user-images.githubusercontent.com/233318/93137369-a4b8c800-f6dd-11ea-9163-5251d6354ec0.png)

**Comment by chemzqm** [comment]
I can't reproduced this with latest coc.nvim and eslint, please upload output of eslint https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by ianchanning** [comment]
So I'm now seeing this bug:

![Screenshot from 2020-09-20 16-31-52](https://user-images.githubusercontent.com/233318/93713881-1cb04380-fb5f-11ea-98a9-cf5b9570a970.png)

It got "stuck" after this error:

`[eslint no-undef] [E] 'c' is not defined. (no-undef)` for when I started typing `const` and then even though I've typed the rest of the line `const checked = value === null ? false : checked;` it stays with the error.

This is the output I get from `:CocCommand workspace.showOutput`, I've created a gist because it's too big to paste: https://gist.github.com/ianchanning/134988a5d3aed9f87a3dfb464682d51b

**Comment by chemzqm** [comment]
The content of document is wrong, maybe you're using old coc.nvim

**Comment by ianchanning** [comment]
`CocInfo`:

```
## versions

vim version: NVIM v0.4.4
node version: v12.18.4
coc.nvim version: 0.0.79-b71489207a
coc.nvim directory: /home/channi16/.vim/bundle/coc.nvim
term: xterm-256color
platform: linux
```

**Comment by ianchanning** [comment]
Indeed - I'm on 0.0.79 vs the 1.31 that is here. But as far as I know I'm just using Plug to pull in the latest version...

```vim
Plug 'neoclide/coc.nvim', {'branch': 'release'}
```

**Comment by BerkeleyTrue** [comment]
I'll add my data as well. Still run into the issue. It also happens when I do a `/` search. The thing I'm searching will throw errors.

```
## versions

vim version: NVIM v0.4.4
node version: v12.18.4
coc.nvim version: 0.0.79-b71489207a
coc.nvim directory: /home/berkeleytrue/.config/nvim/plugged/coc.nvim
term: screen-256color
platform: linux

```

```
  + coc-eslint 1.2.7 ~/.config/coc/extensions/node_modules/coc-eslint
```

**Comment by johnpyp** [comment]
I've been having similar problems for a long time, but it's been getting increasingly common recently from what I can tell. I have autoformatting with eslint and prettier turned on, but another reports that disabling it doesn't fix the issue so it might be related to something else.

**Comment by ianchanning** [comment]
I have currently given up with coc, it's a shame but there's nothing that I can see that is the problem. Perhaps it's something to do with my eslint setup, but I don't think so - I got tsserver errors. Anyway I'm going to switch back to trying with ALE and maybe some other linting plugins to see if they have similar issues.

coc is still the best LSP plugin I used if it works, so I'm hoping there is a fix for this somewhere.

**Comment by chemzqm** [comment]
Could be problem with neovim's buffer lines change event, I can't experience it, try `:e!` to reload the buffer.

**Comment by ianchanning** [comment]
Ok, I'll give that a try, I just did `:CocRestart` each time.

I could also try with Vim instead of Neovim to see if that has the same problems

**Comment by ianchanning** [comment]
I have now hit the same issue almost immediately when running this in Vim 8, so it's not a Neovim problem:

```vim
## versions

vim version: VIM - Vi IMproved 8.2 8021767
node version: v12.19.0
coc.nvim version: 0.0.79-d4d93dc25f
coc.nvim directory: /home/channi16/.vim/bundle/coc.nvim
term: dumb
platform: linux

## Output channel: eslint

[Info  - 14:24:01] ESLint server running in node v12.19.0
[Info  - 14:24:02] ESLint library loaded from: /home/channi16/imec/innovatrix/images/api/node_modules/eslint/lib/api.js
```

I can now get this to break every time.

I start a new line, type `const the` go onto the next line and then hit `Esc` to go back to normal mode.

It then generates errors for the first character I have typed but doesn't clear them.

![Screenshot from 2020-10-16 14-33-32](https://user-images.githubusercontent.com/233318/96258784-d4007480-0fbc-11eb-950b-cf4ad105b2e5.png)

It's as if it thinks all I have typed is `c`, on the second character of the line it has 'missing semi-colon'.

![Screenshot from 2020-10-16 14-36-46](https://user-images.githubusercontent.com/233318/96258912-0ca04e00-0fbd-11eb-8504-853eab3f289b.png)

`:e!` does indeed remove the errors similar to `:CocRestart`, but obviously that is not a solution.

**Comment by chemzqm** [comment]
Can't reproduce, need connection log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc, save your vimrc and exit vim.
* Restart your vim/neovim to make the issue happen.
* Get the log filepath by :echo $NODE_CLIENT_LOG_FILE
* Attach the log file or paste content from the log.

**Comment by ianchanning** [comment]
Thanks for your replies. I did this with Vim8 as I can reproduce the error every time now. Output log file: https://gist.github.com/ianchanning/201cb323e9ae90aec06c37b719f2dac1

**Comment by ianchanning** [comment]
Also I don't know how relevant this is, but normally from what I remember the errors get put into the location list, but here, although I've got 3 errors (the `E:3` in the tagline) there's nothing in the location list

![Screenshot from 2020-10-18 12-00-36](https://user-images.githubusercontent.com/233318/96364164-abea5000-1139-11eb-8654-96ec7691e23c.png)

**Comment by chemzqm** [comment]
Auto change location list was removed, use :CocDiagnistic command to open location list

**Comment by johnpyp** [comment]
Can you try adding `"diagnostic.refreshOnInsertMode": true` to your CocConfig and see if that fixes it?

Admittedly, the issue doesn't happen *a ton* to me, so I'm not sure if it is still occurring, but since adding this I haven't had any stale diagnostics.

**Comment by ianchanning** [comment]
@johnpyp No sadly that doesn't help.

However I have made some progress. If I type really slowly whilst in insert mode and wait for the errors to correct themselves as I am typing before returning to normal mode then it works correctly.

It's only if I type something very fast in insert mode and then quickly switch back to normal mode that it gets stuck with the error messages.

**Comment by chemzqm** [comment]
I have reproduced it with big file, looks like eslint server ignores new text documents when it's too busy.

**Comment by kyle-mccarthy** [comment]
@chemzqm fwiw I am having this issue on a file with only 32 loc; however, it is in a large project

**Comment by benwainwright** [comment]
Hey @chemzqm is there any progress on this? Its a huge detractor for the user experience of `coc.nvim` which would otherwise make vim every bit as good as VsCode?

**Comment by davidsierradz** [comment]
I'm using [iamcco/coc-diagnostic: diagnostic-languageserver extension for coc.nvim](https://github.com/iamcco/coc-diagnostic) for eslint until `coc-eslint` improves on this:

coc-settings.json:
```json
{
"diagnostic.refreshOnInsertMode": true,
"diagnostic.messageDelay": 500,
"diagnostic.refreshAfterSave": false,
"diagnostic-languageserver.filetypes": {
    "javascript": "eslint"
  },
"diagnostic-languageserver.linters": {
    "eslint": {
      "command": "./node_modules/.bin/eslint",
      "rootPatterns": [".git", "package.json"],
      "debounce": 100,
      "args": ["--stdin", "--stdin-filename", "%filepath", "--format", "json"],
      "sourceName": "eslint",
      "parseJson": {
        "errorsRoot": "[0].messages",
        "line": "line",
        "column": "column",
        "endLine": "endLine",
        "endColumn": "endColumn",
        "message": "${message} [${ruleId}]",
        "security": "severity"
      },
      "securities": {
        "2": "error",
        "1": "warning"
      }
    }
  }
}
```

**Comment by benwainwright** [comment]
@davidsierradz Thanks! I'll definitely give that a go. Hope it works!

**Comment by chemzqm** [comment]
Will try to fix after coc.nvim 0.0.80 released.

**Comment by kyle-mccarthy** [comment]
@chemzqm do you know what is causing the problem? I would be willing to help if you were able to narrow down the problem. 

I saw in https://github.com/neoclide/coc.nvim/issues/2662 that it could be an issue with the fastDiff dependency. I pulled this repo down locally and replaced fastDiff and `getChange` with a native implementation using the n-api. It greatly reduces the execution time of getChange, but `coc-eslint` remains really sluggish overall. Do you think it's an issue with eslint in general?

**Comment by chemzqm** [comment]
Could be issue with willSaveUntil, only one language server should be allowed for changes .

**Comment by chemzqm** [comment]
Try coc-eslint 1.4.0, if you still have this issue, open new issue with output of eslint.

**Comment by ianchanning** [comment]
Thank you this is great. I haven't tested it yet but I've done the upgrade. This wasn't obvious to me how to do this. If anyone else is wondering:

1. Update coc.nvim to v0.0.8 - I'm using Plug and so `:PlugUpdate` fixed that. 
2. Re-start neovim 
3. To update `coc-eslint` either re-run `:CocInstall coc-eslint` or `:CocUpdate` will update the coc plugin.

**Comment by ianchanning** [comment]
From what I can tell this is working. It gets into the same state with incorrect errors but they now get cleaned up after a short while.

**Comment by benwainwright** [comment]
Yeah, same here. It appears to be working for me!
