### ISSUE TITLE
Missing floating box for a 'comma-dangle' error message

### ISSUE THREAD

**Issue by iFork** [neoclide/coc-eslint#73]
Diagnostic floating message for 'comma-dangle' error is not displayed while error marker is present in the gutter, it can be jumped to and `:CocDiagnostics` shows the error entry with the message. CodeAction is provided for this error only when invoked for the whole line (not with \<leader\>a\<within line motion\>)

Other errors display their diagnostic message in a floating box when jumped to with `]g`/`[g`.

### `CocCommand workspace.showOutput`
```

Params: {
    "textDocument": {
        "uri": "file:///home/path/to/my/project/dir/test.js",
        "version": 35
    },
    "contentChanges": [
        {
            "text": "const arr = [\n    'a',\n    'b'\n]\n"
        }
    ]
}

Params: {
    "uri": "file:///home/path/to/my/project/dir/test.js",
    "diagnostics": [
        {
            "message": "Missing trailing comma. (comma-dangle)",
            "severity": 1,
            "source": "eslint",
            "range": {
                "start": {
                    "line": 2,
                    "character": 7
                },
                "end": {
                    "line": 3,
                    "character": 0
                }
            },
            "code": "comma-dangle"
        }
    ]
}
```

### versions

coc-eslint 1.3.0 

vim version: VIM - Vi IMproved 8.2 8020856
node version: v14.4.0
coc.nvim version: 0.0.78-9f9d8a32c4
coc.nvim directory: /home/mher/.vim/plugged/coc.nvim
term: dumb
platform: linux

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
