### ISSUE TITLE
Can you add eslint_d support?

### ISSUE THREAD

**Issue by utrumo** [neoclide/coc-eslint#74]
Using eslint_d eslint works almost instantly. Could you add it support to your extension?
https://www.npmjs.com/package/eslint_d

**Comment by chemzqm** [comment]
It is long running process like eslint_d.

**Comment by stellarhoof** [comment]
> It is long running process like eslint_d.

Can you elaborate a bit more?

**Comment by aureooms** [comment]
@chemzqm Does `coc` start a new `eslint` process for each `eslint.run` event?

**Comment by fannheyward** [comment]
Open an ESLint enabled project, ps and grep eslint, the coc-eslint server process run in daemon.

**Comment by chemzqm** [comment]
> @chemzqm Does `coc` start a new `eslint` process for each `eslint.run` event?

There would be eslint process with task like `eslint.lintProject`

**Comment by aureooms** [comment]
> Open an ESLint enabled project, ps and grep eslint, the coc-eslint server process run in daemon.

@fannheyward It seems indeed that there is a single always-running `node` process. No additional processes are spawned during processing of `eslint.run` events.
