### ISSUE TITLE
eslint.quiet does not suppress warnings about no .eslintrc file

### ISSUE THREAD

**Issue by nkhlmn** [neoclide/coc-eslint#75]
When I set `eslint.quiet` to `true` it still shows warnings about not finding a .eslintc file. Is this the expected behavior? If so it would be great to have a way to suppress these warnings.

I'm using nvim 0.4.4 on macOS with the latest version of coc and coc-eslint. Let me know if you need any more info. Thanks!

**Comment by chemzqm** [comment]
It should suppress that warning.
