### ISSUE TITLE
^1.3.0 Broken for Yarn 2 

### ISSUE THREAD

**Issue by jpulec** [neoclide/coc-eslint#77]
# Description
After bumping `coc-eslint` from `1.2.7` to `1.3.0`, the plugin no longer functions. It just issues the standard `Failed to load the ESLint library for the document` error, and doesn't provide a whole lot of other help to understand what might be going wrong. Possibly this is related to the `eslint.runtime` option that was added.

```
## versions

vim version: NVIM v0.4.4
node version: v12.18.2
coc.nvim version: 0.0.79-6cb5c6cd2d
coc.nvim directory: /home/james/.local/share/nvim/plugged/coc.nvim
term: screen
platform: linux
```

**Comment by BenoitZugmeyer** [comment]
A while ago, I submited [this PR](https://github.com/neoclide/coc-eslint/pull/43) to support Yarn 2. But my changes [have been reverted](https://github.com/neoclide/coc-eslint/commit/0a658803c0dcb07e61a6609c2df0cb23bec12637) to fix [an issue to resolve eslint locally](https://github.com/neoclide/coc-eslint/issues/56). I sent comment on the closed issue to try to understand what was not working as expected, and maybe propose a better fix that could also support Yarn 2.
