### ISSUE TITLE
Does not work for heavy loads

### ISSUE THREAD

**Issue by MathiasKandelborg** [neoclide/coc-eslint#79]
I am trying to integrate this with prettier, but every time I fix an error by writing the file, with `fixOnSave` ESLint doesn't update its position and won't remove the error until coc/vim is restarted.

It is working very fine with the TS server, which updates as it should. But building the application can take seconds, and coc-eslint doesn't seem to wait or update after it has tried once, which it does while TS is compiling? I don't know what is going on - after having tried debugging eslint and trying to find how it's run with coc-eslint - but I can say that VSCode works perfectly with the same settings albeit with several seconds slowdown. When waiting for ESLint in VSCode, hovering over an error, I can sometimes see the error updates several times until 'the final decision' is made.

ESLint is unusable when trying to check files constantly, while in an editor, for a large project, it seems. But it was at least possible with VSCode, so I'd love to know _**how I can set a cache for eslint**_, as that seems to be a way to mitigate the problem.

`@typescript-eslint/parser` does not seem to work with coc or coc-eslint.

This is very frustrating. I went to vim because I had gotten tired of all the lag and random unresponsiveness, but experiencing this integration makes me miss the certainty of VSCode **even though I often wait 3-5+ seconds to save/make a change**.

I had Yarn 2 in a workspace setting, which I've reverted to yarn classic without a workspace, but that had absolutely no effect on the performance of coc, so it must be something else. I can enable the only eslint, enter my project, open a file, make an edit only not to get any eslint updates. If I try enabling tsserver, it updates perfectly fine, so the only place to pinpoint is coc-eslint and **how it implements ESLint and how it differs from VSCode**.

**Comment by MathiasKandelborg** [comment]
I can make changes in neovim, write the file, see the errors persist, no amount of changes or extra writes does anything.

If I open the file in any editor and make a change (basically I just need to write file to disk again), coc-eslint updates.

**Comment by MathiasKandelborg** [comment]
I had to actually tell neovim that it my file has been written, after it has been written, because that makes sense?

Here's how I fixed my problem:
```vim
augroup AutoSwap
        autocmd!
        autocmd SwapExists *  call AS_HandleSwapfile(expand('<afile>:p'), v:swapname)
augroup END

function! AS_HandleSwapfile (filename, swapname)
        " if swapfile is older than file itself, just get rid of it
        if getftime(v:swapname) < getftime(a:filename)
                call delete(v:swapname)
                let v:swapchoice = 'e'
        endif
endfunction
autocmd CursorHold,BufWritePost,BufReadPost,BufLeave *
  \ if isdirectory(expand("<amatch>:h")) | let &swapfile = &modified | endif

augroup checktime
    au!
    if !has("gui_running")
        "silent! necessary otherwise throws errors when using command
        "line window.
        autocmd BufEnter,CursorHold,CursorHoldI,CursorMoved,CursorMovedI,FocusGained,BufEnter,FocusLost,WinLeave * checktime
    endif
augroup END
```

Following the issue at: https://github.com/neovim/neovim/issues/2127

I'm sorry for bothering you.

**Comment by kyle-mccarthy** [comment]
@MathiasKandelborg I actually think that this is the same issue as #72 and isn't a neovim problem. Try running `:e` when you have the issue (without your vim config changes) and see if it fixes the problem. 

As a side note, I also can't get the cache to work, I set it just like you did in the coc config file.

**Comment by MathiasKandelborg** [comment]
@kyle-mccarthy That does work, and those settings seemed to work but does not all the time.

There is some work being done at neovim to do things differently ATM, so that might help something.

About the cache, mine is updated from time to time, and the file exists.
I made sure the cache command runs for everything; if you need pointers, I would be happy to look where I have it set to use cache. The cache does speed up my linting for a few files, but not much because
I have a bunch of rules that need heavy work.

**Comment by kyle-mccarthy** [comment]
I would be curious to know how you got your cache working. I initially though the errors weren't disappearing because eslint was slow but according to the other issue it might be a different problem.

I added the `eslint.options` to my coc config but it doesn't seem to create the cache file. My coc config looks like this.

```
{
  ...
  "eslint.options": {
    "cache": true
  }
}
```

**Comment by MathiasKandelborg** [comment]
Yea, the cache file doesn't update with writes, it's only when I run it with other things.

This seems to be a bit odd, because eslint should be running locally, which it seems to be doing (it's loaded from local node_modules). But there's no update to the cache even though I save changes and eslint checks the file. The cache is deleted whenever eslint runs without the cache option (according to eslint), so I'm at a loss here. I need to investigate further to see if the cache is actually being used, but the timing for checking/commit seems to be the same time I wait for eslint to update.
