### ISSUE TITLE
autoFix不管用

### ISSUE THREAD

**Issue by rmGFW** [neoclide/coc-eslint#82]
<img width="453" alt="image" src="https://user-images.githubusercontent.com/66858140/98380845-12e98d80-2084-11eb-9738-5c82f969b008.png">

我已经在coc-settings.json 添加了这个配置
可是我保存js 文件并不会自动格式化

**Comment by toby-wollit** [comment]
This might have something to do with autoFixOnSave being deprecated in eslint 2.0.4 https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

Vscode now uses:
```
 "editor.codeActionsOnSave": {
        "source.fixAll": true
    }
```

**Comment by Dema** [comment]
Yeah, something got broken since like a week or so. `:CocCommand eslint.executeAutofix` works but fix on save is broken

**Comment by chemzqm** [comment]
Eslint doesn't do format.

**Comment by toby-wollit** [comment]
@chemzqm could you explain what you mean please?

**Comment by chemzqm** [comment]
It only works with saved files, could be the problem you got.

**Comment by toby-wollit** [comment]
No, the files I'm working on are saved and it used to work until recently. I've had to add this to my vimrc to temporarily fix the behaviour:

```autocmd BufWritePre *.{js,jsx,ts,tsx} if exists(":CocAction") | :call CocAction('runCommand', 'eslint.executeAutofix') | sleep 100m | endif
```

**Comment by Dema** [comment]
@chemzqm Could you, please, reopen the ticket. It is not about "formatting", it's about autoFixOnSave being broken. I've tried to bisect the issue but kind of failed. I tried downgrading eslint-coc while having latest coc and it doesn't work. I failed to downgrade coc deep enough to find a working combo. :cry: I've had typescript errors with Promise.resolve() demanding non-empty first argument.

**Comment by chemzqm** [comment]
You have to create autocmd yourself if you want it always works https://github.com/neoclide/coc.nvim/issues/2704.

VSCode changed to use source code actions, but we don't have yet.

**Comment by toby-wollit** [comment]
Do you plan on implementing source code actions?

**Comment by Dema** [comment]
Aah, I see, you've already removed the CocConfig option `"eslint.autoFix": true,` Thanks! I'll add the autocmd!

As for source code actions, I actually switched to neovim+CoC because of them :smile:. My VSCode freezes for about 10-20 seconds on "Getting source actions from eslint" when I save a typescript file
