### ISSUE TITLE
How to confirm/echo the eslint version used by coc-eslint

### ISSUE THREAD

**Issue by EdmundsEcho** [neoclide/coc-eslint#84]
The `CocInfo` reports the location *of the extension* and error status of the `eslint` instance.  

However, I'm not clear whether the extension uses the same eslint instance as what is used in my project.  My project  uses a project-specific eslint instance.  

To help understand what is going on, how might I echo the version of the eslint version referenced by the `coc-eslint` extension? 

Thank you in advance to anyone with some experience here. 

\- E

**Comment by chemzqm** [comment]
Check out output

**Comment by chemzqm** [comment]
Use `:CocCommand workspace.showOutput`

**Comment by EdmundsEcho** [comment]
Perfect output - complete and intuitive!  Thank you!!
