### ISSUE TITLE
does the fix command only include eslint-warnings?

### ISSUE THREAD

**Issue by EdmundsEcho** [neoclide/coc-eslint#85]
The coc-eslint fix documentation indicates that fixes will occur to eslint issues:warning.  

>The extension supports automatic fixing of *warnings* to the extent that it is supported by eslint.

Does that mean eslint issues:error will be ignored by the coc fix engine?  

I ask because with the changes to CRA v4 and Eslint 7, what were warnings are now errors in what is being transpiled.  Coincidentally, what was, pre-upgrade, fixed for me on save, no longer are.  

I'm trying to figure out if the coincidence, is in fact the cause of my loss in auto-fix capacity.  

Thank you.

\- E

**Comment by chemzqm** [comment]
Don't know, simply try `eslint --fix` in your terminal to see if that issue can be fixed.

**Comment by OJFord** [comment]
Does anything get fixed/formatted for you? I've only just tried it (so don't have experience with an older version) but nothing is being fixed, where `eslint --fix` does.
