### ISSUE TITLE
eslint.filetypes - active extension when working on "other" filetypes

### ISSUE THREAD

**Issue by EdmundsEcho** [neoclide/coc-eslint#87]
When I work on a `toml` or `rust` or `md` file for instance, the `CocList extensions` reports that `coc-eslint` is active.  My list of extensions in the `CocConfig` only includes javascript-related files (the default values).  

```json
  "eslint.filetypes": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ],
```

Is there another setting that might be overriding the config?

Thanks for letting me know.

\- E

**Comment by chemzqm** [comment]
The `activationEvents` is `*`, you can configure `"eslint.filetypes"`

**Comment by EdmundsEcho** [comment]
If I understand correctly, the solution is to set "eslint.filetypes"?  If so, I have done that per the original post. In your experience is there something else I should look at?

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by EdmundsEcho** [comment]
Thank you!
