### ISSUE TITLE
[coc.nvim] ESLint: Failed to load config "airbnb-base" to extend from.

### ISSUE THREAD

**Issue by cytommi** [neoclide/coc-eslint#89]
I get this error whenever I open up a .js file in my project

**[coc.nvim] ESLint: Failed to load config "airbnb-base" to extend from. Referenced from: /file_path_to_project/.eslintrc.js. Please see the 'ESLint' output channel for details.**
 
Here's the line in my .eslint.js that extends from airbnb-base
`module.exports = {extends: ['airbnb-base', 'prettier']` 

 
I am quite new to this so please let me know if you need any clarification. Thanks!

**Comment by chemzqm** [comment]
Seems you don't have airbnb-base module installed.

**Comment by cytommi** [comment]
Here are my dev dependencies listed in package.json
`    "eslint": "^7.13.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^6.12.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-prettier": "^3.1.2",
`
I've run `yarn install` but that doesn't seem to fix it. Thanks for the quick response.
