### ISSUE TITLE
how make it work?

### ISSUE THREAD

**Issue by dementor5** [neoclide/coc-eslint#9]
Do not work with local and global installed eslint.
[coc.nvim
cocOpenLog:
```
2019-04-08T15:05:17.150 ERROR (pid:27447) [commands] - Error: Language client is not ready yet
    at LanguageClient.sendRequest (/home/user/.vim/plugged/coc.nvim/build/index.js:65643:19)
    at Object.<anonymous> (/home/user/.config/coc/extensions/node_modules/coc-eslint/lib/index.js:206:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/.config/coc/extensions/node_modules/tslib/tslib.js:104:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by chemzqm** [comment]
You can't run `eslint.executeAutofix` before client ready.

**Comment by dementor5** [comment]
This plug-in does not work for me at all. it is normal?
it for the present is not ready at all?

**Comment by chemzqm** [comment]
> This plug-in does not work for me at all

You need provide result from `:CocInfo` and output from eslint, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

I can't reproduce your problem.

**Comment by dementor5** [comment]
how can I make more detailed and useful the log?
```
coc-settings.json
{
  "eslint.trace.server": "verbose",
}
```
cocinfo:
```
## versions

vim version: NVIM v0.4.0-dev
node version: v10.15.3
coc.nvim version: 0.0.64-615c4b2d9d
term: xterm-256color
platform: linux

## Error messages

## Output channel: tsserver
[Info  - 3:26:02 PM] Forking TSServer
PATH: /home/user/.yarn/bin:/home/user/.config/yarn/global/node_modules/.bin:/home/user/.yarn/bin:/home/user/.config/yarn/global/node_modules/.bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/.config/composer/vendor/bin 
[Info  - 3:26:02 PM] Started TSServer
{
  "path": "/home/user/myProject/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.3.1",
    "version": "3.3.1"
  }
}
```

**Comment by chemzqm** [comment]
Try `:CocCommand workspace.showOutput eslint`.

**Comment by dementor5** [comment]
> Try `:CocCommand workspace.showOutput eslint`.

I received such error:
`[coc.nvim] Channel "eslint" not found`

**Comment by chemzqm** [comment]
You need to edit some javascript file to make the server start.

**Comment by dementor5** [comment]
> You need to edit some javascript file to make the server start.

I am ready. What to begin with?

**Comment by chemzqm** [comment]
Try edit and save javascript file, then paste result from `:CocInfo`

**Comment by dementor5** [comment]
Tried with .js the file - works!
```
## versions

vim version: NVIM v0.4.0-dev
node version: v10.15.3
coc.nvim version: 0.0.64-615c4b2d9d
term: screen-256color
platform: linux

## Error messages

## Output channel: tsserver[Info  - 6:49:00 PM] Forking TSServer
PATH: /home/user/.yarn/bin:/home/user/.config/yarn/global/node_modules/.bin:/home/user/.yarn/bin:/home/user/.config/yarn/global/node_modules/.bin:/home/user/.yarn/bin:/home/user/.config/yarn/global/node_modules/.bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/.config/composer/vendor/bin 
[Info  - 6:49:00 PM] Started TSServer
{
  "path": "/home/user/myProject/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.3.1",
    "version": "3.3.1"
  }
}


## Output channel: eslint[Info  - 6:49:00 PM] ESLint server running in node v10.15.3
[Info  - 6:49:01 PM] ESLint library loaded from: /home/user/myProject/node_modules/eslint/lib/api.js
```
The problem with .ts files turns out.
For .ts with eslint i use:
```
"@typescript-eslint/eslint-plugin": "^1.3.0",
"@typescript-eslint/parser": "^1.3.0",
```
My eslint config for ts is .eslintrc.yml:
```
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint']

parserOptions:
  project: 'tsconfig.json'

env:
  browser: true
  node: false

extends: 'plugin:@typescript-eslint/recommended'

rules: {
  'indent': 'off',
  '@typescript-eslint/indent': ['error', 2]
}
```

**Comment by chemzqm** [comment]
It does work for typescript files, you need https://github.com/neoclide/coc-tslint-plugin

**Comment by dementor5** [comment]
tslint not now, but in future will depricated.
https://github.com/palantir/tslint/issues/4534

I think that the possibility of processing .ts files by this plug-in with eslint is necessary...

**Comment by dementor5** [comment]
I tried, ~ unfortunately does not work. :(
This plug-in very much lacks more friendly way of connection of third-party plug-ins.

**Comment by chemzqm** [comment]
Did you confugure eslint.filetypes settings?

**Comment by dementor5** [comment]
> Did you confugure eslint.filetypes settings?

Here, what is necessary! I registered this line in coc-settings.json:
`  "eslint.filetypes": ["javascript", "javascriptreact", "typescript"]`
 and now everything works. Thanks! :)

**Comment by livdevan** [comment]
I've got the same problem but "eslint.filetypes" does not solve it, the plugin works only for js types in my case, when I edit a js files tsserver and eslint channel start automatically, but ts files simply are not recognized, if I try to run eslint I see "Language Client is not ready yet"

**Comment by livdevan** [comment]
Got it finally, I missed typescript syntax support. 
coc-slint and coc-tsserver start working after I Installed yats.vim

**Comment by chemzqm** [comment]
Not syntax, but filetype.

**Comment by ahayman** [comment]
FYI - coc-eslint does not support eslint v8.x (as of the the time this was written).  Latest you can use is v7.x.  Took me a while to figure this out.
