### ISSUE TITLE
use diagnostic.level cofig to control levels

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc-eslint#90]
currently when `eslint.quiet` is set to true, it filters out warnings, but coc.nvim already has `diagnostic.level` settings, so I think it's better to use that config to control diagnostic levels, `quiet` maybe should only be used to ignore errors and bad configs etc

**Comment by chemzqm** [comment]
No, it's eslint specific configuration

**Comment by GopherJ** [comment]
@chemzqm ok thanks, I always want quiet to do just what it should do but don't touch diagnostics...
