### ISSUE TITLE
[BREAK CHANGE] eslint not validate current workspace by default

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc-eslint#98]
Invoke `:CocCommand eslint.showOutputChannel` to choose active state for your current workspace,  it does the same as click status line item from vscode-eslint.

**Comment by realvikas** [comment]
IMO, It would be better if it automatically asks for the input. Like how `coc-rust-analyzer` asks to download the new version of `rust-analyzer`.

**Comment by chemzqm** [comment]
No, most of vim user don't like disturb.
