### ISSUE TITLE
Does no longer run on save

### ISSUE THREAD

**Issue by pjg** [neoclide/coc-eslint#99]
Something broke with latest updates and coc-eslint does no longer execute linting on save, even though I have it enabled in the config. I'm using all latest versions.

My config:

```
  "eslint.autoFixOnSave": true,
  "eslint.filetypes": ["javascript", "javascriptreact", "javascript.jsx", "javascript.tsx"],
  "eslint.validate": ["javascript", "javascriptreact", "javascript.jsx", "javascript.tsx"],
  "eslint.run": "onSave",
  "prettier.eslintIntegration": true,
  "tsserver.formatOnType": false
```

**Comment by codejunkienick** [comment]
I have same issue, downgrading to 1.3.2 resolves autoFixOnSave.

**Comment by pjg** [comment]
Just doing `npm install coc-eslint@1.3.2 ` didn't work for me. I had to do `rm -rf ./node_modules/coc-eslint` first.

**Comment by random143** [comment]
I see. I thought I was the only one who have this experience. How can I install a specific version using CocInstall?

**Comment by chemzqm** [comment]
`"eslint.run": "onSave"` works as expected for me, but `eslint.autoFixOnSave` is broken with it.

**Comment by iamcco** [comment]
Run `CocCommand eslint.showOutputChannel` command to select lib, this fix for me.

**Comment by pjg** [comment]
https://github.com/neoclide/coc-eslint/commit/b0e4270771797acbebcda2aeab0ee26347418064 fixed it, thanks!
